export const ROUTE_LOGIN = "login"
export const ROUTE_TAB = "tab"
export const ROUTE_LISTINGS = "listings"
export const ROUTE_MY_LISTINGS = "my-listings"
export const ROUTE_LISTING_DETAILHS = "listing-details"